services:
  mysql:
    image: mysql:8.4
    container_name: clientes_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes_user
      MYSQL_PASSWORD: clientes_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_clientes_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: clientes_api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientes_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: clientes_user
      SPRING_DATASOURCE_PASSWORD: clientes_pass
    ports:
      - "8081:8080"

volumes:
  mysql_clientes_data:
